
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.1 EDK_MS1.53d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xps2.h"

/*
* The configuration table for devices
*/

XPs2_Config XPs2_ConfigTable[] =
{
	{
		XPAR_PS2_0_DEVICE_ID,
		XPAR_PS2_0_BASEADDR
	},
	{
		XPAR_PS2_1_DEVICE_ID,
		XPAR_PS2_1_BASEADDR
	}
};

